packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - "@expo/ui@57.0.2"
  - expo-dev-client@57.0.4
  - expo-dev-launcher@57.0.4
  - expo-dev-menu@57.0.4
saveExact: true
